@startuml

scale 1.1
title Reactive Streams
hide footbox
skinparam monochrome true
'skinparam defaultFontName Source Sans Pro
'skinparam titleFontSize 15
skinparam sequenceMessageAlign center

'skinparam sequence {
'ArrowColor black
'ActorBorderColor black
'LifeLineBorderColor black
'LifeLineBackgroundColor black
'
'ParticipantBorderColor black
'ParticipantBackgroundColor white
'ParticipantFontColor black
'}

participant Publisher
participant Subscription
participant Subscriber

Subscriber -> Publisher : subscribe()
Publisher -> Subscription : new()
Publisher -> Subscriber : onSubscribe(Subscription)

loop until completed
Subscriber -> Subscription : request(int)
Subscription -> Publisher

alt no error
Publisher -> Subscriber : onNext(T)
else error
Publisher -> Subscriber : onError(Throwable)
end

alt cancel subscription
Subscriber -> Subscription : cancel()
Subscription -> Publisher
end

end

Publisher -> Subscriber : onComplete()

@enduml