@startuml

scale 1.0
set namespaceSeparator none

skinparam monochrome true
skinparam ClassBackgroundColor white
skinparam ClassBorderColor black
skinparam CircledCharacterFontStyle normal

interface Publisher<T> {
+ void subscribe(Subscriber<? super T> subscriber)
}

interface Subscriber<T> {
+ void onSubscribe(Subscription subscription)
+ void onNext(T item)
+ void onError(Throwable throwable)
+ void onComplete()
}

interface Subscription {
+ void request(long n)
+ void cancel()
}

interface Processor<T, R> {
}

Publisher <|-- Processor
Subscriber <|-- Processor

@enduml
