@startuml

skinparam linetype ortho
skinparam RectangleBackgroundColor white
skinparam RectangleBorderColor black
skinparam RectangleFontName Source Sans Pro
skinparam ArrowColor black

center header
data, error, completion events
end header

center footer
backpressure events
end footer

rectangle Publisher {
}

rectangle Processor1 {
}

rectangle Processor2 {
}

rectangle ProcessorN {
}

rectangle Subscriber {
}

Publisher <- Processor1
Publisher -right> Processor1

Processor1 <- Processor2
Processor1 -right> Processor2

Processor2 <. ProcessorN
Processor2 .right> ProcessorN

ProcessorN <- Subscriber
ProcessorN -right> Subscriber

@enduml
