@startuml

scale 1.2
hide footbox

!pragma teoz true

skinparam monochrome true
skinparam defaultFontName Source Sans Pro
skinparam sequenceMessageAlign center
skinparam participantBackgroundColor #white
skinparam noteBackgroundColor #white
skinparam sequenceGroupBackgroundColor #white
skinparam participantPadding 10

participant Observable
participant Subscription
participant Observer

Observer ->(10) Observable : subscribe(Observer)
Observable ->(10) Subscription : new Subscription()
Observable ->(10) Observer : onSubscribe(Subscription)

Observable ->(10) Observer : onNext(T)
Observable ->(10) Observer : onNext(T)
Observable ->(10) Observer : onNext(T)

alt
    Observable ->(10) Observer : onError(Throwable)
else
    Observable ->(10) Observer : onComplete()
else
    Observer ->(10) Subscription : cancel
end

@enduml
