@startuml

scale 1.0
hide footbox

!pragma teoz true

skinparam monochrome true
skinparam defaultFontName Source Sans Pro
skinparam sequenceMessageAlign center
skinparam participantBackgroundColor #white
skinparam noteBackgroundColor #white
skinparam sequenceGroupBackgroundColor #white
skinparam participantPadding 20

participant Caller
participant Target

Caller ->(10) Target : next(long)
Target ->(10) Caller : value
Target ->(10) Caller : value
Target ->(10) Caller : value

Caller ->(10) Target : next(long)
Target ->(10) Caller : value
Target ->(10) Caller : value

alt
Target ->(10) Caller : value
else
Target -->(10) Caller : error
else
Target -->(10) Caller : no value
end

@enduml
