@startuml
!include sequence_diagram_header.iuml

skinparam participantPadding 10

participant Publisher
participant Subscription
participant Subscriber

Subscriber ->>(10) Publisher : subscribe(Subscriber)
Publisher ->>(10) Subscription : new Subscription()
Publisher ->>(10) Subscriber : onSubscribe(Subscription)

Publisher ->>(10) Subscriber : onNext(T)
Publisher ->>(10) Subscriber : onNext(T)
Publisher ->>(10) Subscriber : onNext(T)

alt
    Publisher ->>(10) Subscriber : onError(Throwable)
else
    Publisher ->>(10) Subscriber : onComplete()
else
    Subscriber ->>(10) Subscription : unsubscribe()
end

@enduml
